[package]
name = "logger"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger="0.11.1"
log="0.4.20"
chrono="0.4.33"
termcolor="1.4.1"
once_cell="*"